In [1]:
import numpy as np

In [2]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])

In [3]:
print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [4]:
v_add = v1 + v2
v_sub = v1 - v2

In [5]:
print(v_add)
print(v_sub)

[5 7 9]
[-3 -3 -3]


In [7]:
scalar = 2
v_scaled = scalar*v1

In [8]:
print(v_scaled)

[2 4 6]


In [9]:
dot_product = np.dot(v1,v2)

In [10]:
print(dot_product)

32


In [11]:
magnitude_v1 = np.linalg.norm(v1)
print(magnitude_v1)

3.7416573867739413


In [13]:
A = np.array([[1,2,3], [4,5,6]])
print(A)
print()
B = np.array([[7,8,9], [10,11,12], [13,14,15]])
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [14]:
C = np.array([[1,2,3], [4,5,6]])
matrix_add = A + C
matrix_sub = A - C

print("A+C=\n", matrix_add)
print("A-C=\n", matrix_sub)

A+C=
 [[ 2  4  6]
 [ 8 10 12]]
A-C=
 [[0 0 0]
 [0 0 0]]


In [16]:
matrix_mul = np.dot(A,B)
print(matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [17]:
transpose_A = A.T
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
A = np.array([[2, 3, 0], [4, -1, 0], [1, 1, 0]])
b = np.array([5, 3, 2])
print(A)
print(b)
print()

x = np.linalg.solve(A, b)
print(x)

[[ 2  3  0]
 [ 4 -1  0]
 [ 1  1  0]]
[5 3 2]



LinAlgError: Singular matrix